src/Entity/Acteur.php
<?php

namespace App\Entity;

use App\Repository\ActeurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ActeurRepository::class)
 */
class Acteur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $born;

    /**
     * @ORM\OneToMany(targetEntity=Casting::class, mappedBy="acteur")
     */
    private $castings;

    public function __construct()
    {
        $this->castings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getBorn(): ?\DateTimeInterface
    {
        return $this->born;
    }

    public function setBorn(\DateTimeInterface $born): self
    {
        $this->born = $born;

        return $this;
    }

    /**
     * @return Collection<int, Casting>
     */
    public function getCastings(): Collection
    {
        return $this->castings;
    }

    public function addCasting(Casting $casting): self
    {
        if (!$this->castings->contains($casting)) {
            $this->castings[] = $casting;
            $casting->setActeur($this);
        }

        return $this;
    }

    public function removeCasting(Casting $casting): self
    {
        if ($this->castings->removeElement($casting)) {
            // set the owning side to null (unless already changed)
            if ($casting->getActeur() === $this) {
                $casting->setActeur(null);
            }
        }

        return $this;
    }
    public function __toString(): ?string
    {
        return $this-> prenom;
    }
}

src/Entity/Film.php
<?php

namespace App\Entity;

use App\Repository\FilmRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FilmRepository::class)
 */
class Film
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $titre;

    /**
     * @ORM\Column(type="time")
     */
    private $duree;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $synopsis;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_sortie;

    /**
     * @ORM\ManyToOne(targetEntity=Realisateur::class, inversedBy="films")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_realisateur;

    /**
     * @ORM\OneToMany(targetEntity=Casting::class, mappedBy="film")
     */
    private $castings;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $affiche;

    public function __construct()
    {
        $this->castings = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDuree(): ?\DateTimeInterface
    {
        return $this->duree;
    }

    public function setDuree(\DateTimeInterface $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(?string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->date_sortie;
    }

    public function setDateSortie(\DateTimeInterface $date_sortie): self
    {
        $this->date_sortie = $date_sortie;

        return $this;
    }

    public function __toString(): ?string
    {
        return $this-> titre;
    }

    public function getIdRealisateur(): ?Realisateur
    {
        return $this->id_realisateur;
    }

    public function setIdRealisateur(?Realisateur $id_realisateur): self
    {
        $this->id_realisateur = $id_realisateur;

        return $this;
    }

    /**
     * @return Collection<int, Casting>
     */
    public function getCastings(): Collection
    {
        return $this->castings;
    }

    public function addCasting(Casting $casting): self
    {
        if (!$this->castings->contains($casting)) {
            $this->castings[] = $casting;
            $casting->setFilm($this);
        }

        return $this;
    }

    public function removeCasting(Casting $casting): self
    {
        if ($this->castings->removeElement($casting)) {
            // set the owning side to null (unless already changed)
            if ($casting->getFilm() === $this) {
                $casting->setFilm(null);
            }
        }

        return $this;
    }

    public function getAffiche(): ?string
    {
        return $this->affiche;
    }

    public function setAffiche(string $affiche): self
    {
        $this->affiche = $affiche;

        return $this;
    }
}

src/Form/FilmType.php
<?php

namespace App\Form;

use App\Entity\Film;
use App\Entity\Realisateur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;

class FilmType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre', TextType::class )
            ->add('duree', TimeType::class)
            ->add('synopsis', TextType::class)
            ->add('date_sortie', DateType::class, [
                'widget' => 'single_text'
            ])
            ->add('id_realisateur', EntityType::class,[
                'class' => Realisateur::class,
                'choice_label' => 'nom'
            ])
            ->add('affiche', UrlType::class)
            ->add('valider', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Film::class,
        ]);
    }
}

src/Controller/FilmController.php
<?php

namespace App\Controller;

use App\Entity\Film;
use App\Form\FilmType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class FilmController extends AbstractController
{
    /**
     * @Route("/film", name="app_film")
     */
    public function index(): Response
    {
        return $this->render('film/index.html.twig', [
            'controller_name' => 'FilmController',
        ]);
    }


    /**
     * @Route("/film/show", name="show_film")
     */
    public function showFilm(ManagerRegistry $doctrine): Response{

        $films = $doctrine -> getRepository(Film::class)->findAll();

        return $this->render('film/show.html.twig', [
            'films' => $films,
        ]);
    }

    /**
     * @Route("/film/add", name="add_film")
     * @Route("/film/update/{id}", name="update_film")
     */
    public function add(ManagerRegistry $doctrine, Film $film = null, Request $request): Response{
        
        if(!$film) { // si l'entreprise n'existe pas alors tu l'ajoute
            $film = new Film(); // si l'entreprise déjà il va recup les données de lentreprise existante. 
        }


        $entityManager = $doctrine->GetManager();
        $form = $this-> createForm(FilmType::class, $film);
        $form -> handleRequest($request);

        if($form -> isSubmitted() && $form -> isValid()){

            $film = $form -> getData();
            $entityManager -> persist($film);
            $entityManager -> flush();

            return $this->redirectToRoute('app_film');
        }

        return $this->render('film/add.html.twig', [
                'FormFilm'=> $form ->createView()
        ]);
    }

    /**
     * @Route("/film/{id}", name="detail_film")
     */
    public function show(Film $film): Response
    {
        
        
        
        return $this->render('film/detail.html.twig', [
            'film' => $film,
        ]);
    }

    /**
     * @Route("/film/delete/{id}", name="delete_film")
     */
    public function delete(ManagerRegistry $doctrine, Film $film){
        $entityManager = $doctrine->getManager();
        $entityManager -> remove($film);
        $entityManager -> flush();
        return $this-> redirectToRoute("app_film");
    }

}

templates/film/add.html.twig
{% extends 'base.html.twig' %}
{% block title %} Ajout d'un Film {% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="nav">
<a href=" {{ path('show_film') }} "> Liste des Films </a><br>
<a href=" {{ path('show_realisateur') }} "> Liste des Realisateurs </a><br>
<a href=" {{ path('show_genre') }} "> Liste des Genres </a><br>
<a href=" {{ path('show_acteur') }} "> Liste des Acteurs </a><br>
<a href=" {{ path('show_personnages') }} "> Liste des personnages </a>
<hr>
</div>
<div class="example-wrapper">
    <h1>Ajouter un Film</h1>


    {{form(FormFilm)}}
{% endblock %}

templates/film/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %} Détails {% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="nav">
<a href=" {{ path('show_film') }} "> Liste des Films </a><br>
<a href=" {{ path('show_realisateur') }} "> Liste des Realisateurs </a><br>
<a href=" {{ path('show_genre') }} "> Liste des Genres </a><br>
<a href=" {{ path('show_acteur') }} "> Liste des Acteurs </a><br>
<a href=" {{ path('show_personnages') }} "> Liste des personnages </a>
<hr>
</div>
<div class="example-wrapper">
    <h1>Détail du Film</h1>

 <h1>{{ film }}</h1>
     <img src="{{film.affiche}}">
    <p> Titre : {{ film.titre}}</p>
    <p> Durée : {{ film.duree | date("H:i", "Europe/Paris")}}</p> 
    <p> Date de Création : {{film.dateSortie | date('Y-m-d')}}</p><br>
    <p> Synopsis : <br>{{film.synopsis}}</p>
           
         <h2> Réalisateur </h2>
    {% if film.idrealisateur | length > 0 %}
        {# {% for realisateur in film.idrealisateur %} #}
            {{ film.idrealisateur }} {{film.idrealisateur.prenom}}
        {# {% endfor %} #}
        {% else %}
            <p> Aucun film insérer pour ce réalisateur. </p>
    {% endif %}
     
     <h2> Rôle et Acteur </h2>

     {% for casting in film.castings %}
        <a href="{{ path('detail_acteur', {'id': casting.acteur.id}) }}">{{ casting.acteur }} {{casting.acteur.nom}}</a> Dans le rôle de <a href="{{ path('detail_personnage', {'id': casting.personnage.id}) }}">{{casting.personnage}}</a><br>
     {% endfor %}
 
{% endblock %}

templates/film/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello Liste des lites !{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello ! </h1>
<h2> Bienvenu dans l'antre de DAVYJONES Tintintinnn</h2>

<p> Mon premier projet symfony sans guidage<p>
<div class="nav">
<a href=" {{ path('show_film') }} "> Liste des Films </a><br>
<a href=" {{ path('show_realisateur') }} "> Liste des Realisateurs </a><br>
<a href=" {{ path('show_genre') }} "> Liste des Genres </a><br>
<a href=" {{ path('show_acteur') }} "> Liste des Acteurs </a><br>
<a href=" {{ path('show_personnages') }} "> Liste des personnages </a>
<hr>
</div>
{% endblock %}

templates/film/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FilmController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="nav">
<a href=" {{ path('show_film') }} "> Liste des Films </a><br>
<a href=" {{ path('show_realisateur') }} "> Liste des Realisateurs </a><br>
<a href=" {{ path('show_genre') }} "> Liste des Genres </a><br>
<a href=" {{ path('show_acteur') }} "> Liste des Acteurs </a><br>
<a href=" {{ path('show_personnages') }} "> Liste des personnages </a>
<hr>
</div>
<div class="example-wrapper">
    <h1>Liste des Films</h1>
<br>
<h2><a href="{{ path('add_film') }}">Ajouter un Film</a><br></h2>

{% for film in films %}
    
    <a href="{{ path('detail_film', {'id': film.id}) }}">{{film.titre}}</a> <a href="{{ path('delete_film',{'id': film.id}) }}">Supprimer</a> <a href="{{ path('update_film',{'id': film.id}) }}">Editer</a> <br>

{% endfor %}
{% endblock %}