src/Entity/Acteur.php
<?php

namespace App\Entity;

use App\Repository\ActeurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ActeurRepository::class)
 */
class Acteur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $born;

    /**
     * @ORM\OneToMany(targetEntity=Casting::class, mappedBy="acteur")
     */
    private $castings;

    public function __construct()
    {
        $this->castings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getBorn(): ?\DateTimeInterface
    {
        return $this->born;
    }

    public function setBorn(\DateTimeInterface $born): self
    {
        $this->born = $born;

        return $this;
    }

    /**
     * @return Collection<int, Casting>
     */
    public function getCastings(): Collection
    {
        return $this->castings;
    }

    public function addCasting(Casting $casting): self
    {
        if (!$this->castings->contains($casting)) {
            $this->castings[] = $casting;
            $casting->setActeur($this);
        }

        return $this;
    }

    public function removeCasting(Casting $casting): self
    {
        if ($this->castings->removeElement($casting)) {
            // set the owning side to null (unless already changed)
            if ($casting->getActeur() === $this) {
                $casting->setActeur(null);
            }
        }

        return $this;
    }
    public function __toString(): ?string
    {
        return $this-> prenom;
    }
}

src/Controller/ActeurController.php
<?php

namespace App\Controller;

use App\Entity\Acteur;
use App\Form\ActeurFormType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ActeurController extends AbstractController
{
    /**
     * @Route("/acteur", name="app_acteur")
     */
    public function index(): Response
    {
        return $this->render('acteur/index.html.twig', [
            'controller_name' => 'ActeurController',
        ]);
    }

    /**
     * @Route("/acteur/show", name="show_acteur")
     */
    public function showActeur(ManagerRegistry $doctrine): Response{

        $acteurs = $doctrine -> getRepository(Acteur::class)->findAll();

        return $this->render('acteur/show.html.twig', [
            'acteurs' => $acteurs,
        ]);
    }

    /**
     * @Route("/acteur/add", name="add_acteur")
     * @Route("/acteur/update/{id}", name="update_acteur")
     */
    public function add(ManagerRegistry $doctrine, Acteur $acteur = null, Request $request): Response{
        
        if(!$acteur) { // si l'entreprise n'existe pas alors tu l'ajoute
            $acteur = new Acteur(); // si l'entreprise déjà il va recup les données de lentreprise existante. 
        }


        $entityManager = $doctrine->GetManager();
        $form = $this-> createForm(ActeurFormType::class, $acteur);
        $form -> handleRequest($request);

        if($form -> isSubmitted() && $form -> isValid()){

            $acteur = $form -> getData();
            $entityManager -> persist($acteur);
            $entityManager -> flush();

            return $this->redirectToRoute('app_acteur');
        }

        return $this->render('acteur/add.html.twig', [
                'FormActeur'=> $form ->createView()
        ]);
    }
        /**
     * @Route("/acteur/{id}", name="detail_acteur")
     */
    public function show(Acteur $acteur): Response
    {
        
        
        
        return $this->render('acteur/detail.html.twig', [
            'acteur' => $acteur,
        ]);
    }
}

templates/acteur/add.html.twig
{% extends 'base.html.twig' %}
{% block title %} Ajout d'un Acteur {% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<div class="nav">
<a href=" {{ path('show_film') }} "> Liste des Films </a><br>
<a href=" {{ path('show_realisateur') }} "> Liste des Realisateurs </a><br>
<a href=" {{ path('show_genre') }} "> Liste des Genres </a><br>
<a href=" {{ path('show_acteur') }} "> Liste des Acteurs </a><br>
<a href=" {{ path('show_personnages') }} "> Liste des personnages </a>
<hr>
</div>
<div class="example-wrapper">
    <h1>Ajouter un Acteur</h1>


    {{form(FormActeur)}}
{% endblock %}

templates/acteur/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %} Détails {% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="nav">
<a href=" {{ path('show_film') }} "> Liste des Films </a><br>
<a href=" {{ path('show_realisateur') }} "> Liste des Realisateurs </a><br>
<a href=" {{ path('show_genre') }} "> Liste des Genres </a><br>
<a href=" {{ path('show_acteur') }} "> Liste des Acteurs </a><br>
<a href=" {{ path('show_personnages') }} "> Liste des personnages </a>
<hr>
</div>
<div class="example-wrapper">
    <h1>Détail de l'Acteur :</h1>

 <h1>{{ acteur }}</h1>

    <p> Nom : {{ acteur.nom}}</p>
    <p> Prénom : {{ acteur.prenom }}</p> 
    <p> Date de Naissance : {{acteur.born | date('Y-m-d')}}</p><br>

         <h2> Personnage Joué </h2>
     {% if acteur.castings | length > 0 %}
         {% for casting  in acteur.castings %} 
            {{ casting.personnage }} 
         {% endfor %} 
         {% else %}
             <p> Aucun film insérer pour ce réalisateur. </p> 
     {% endif %}  
     

{% endblock %}

templates/acteur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ActeurController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/laragon/www/cinemasymfony/src/Controller/ActeurController.php'|file_link(0) }}">src/Controller/ActeurController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/laragon/www/cinemasymfony/templates/acteur/index.html.twig'|file_link(0) }}">templates/acteur/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/acteur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FilmController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="nav">
<a href=" {{ path('show_film') }} "> Liste des Films </a><br>
<a href=" {{ path('show_realisateur') }} "> Liste des Realisateurs </a><br>
<a href=" {{ path('show_genre') }} "> Liste des Genres </a><br>
<a href=" {{ path('show_acteur') }} "> Liste des Acteurs </a><br>
<a href=" {{ path('show_personnages') }} "> Liste des personnages </a>
<hr>
</div>
<div class="example-wrapper">
    <h1>Liste des Acteurs</h1>
<br>
<h2><a href="{{ path('add_acteur') }}">Ajouter un Acteur</a><br></h2>

{% for acteur in acteurs %}
    
    <a href="{{ path('detail_acteur', {'id': acteur.id}) }}">{{acteur.nom}} {{acteur.prenom}}</a><br> 
    {# <a href="{{ path('delete_film',{'id': film.id}) }}">Supprimer</a> <a href="{{ path('update_film',{'id': film.id}) }}">Editer</a> <br> #}

{% endfor %}
{% endblock %}